### PR TITLE
1430 search link url

### LINKED ISSUE #1430: Onestop search by object key
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       retrieve metadata by object key
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>reference other systems and their unique ids</td>
  </tr>
</table>

## Tasks
- [ ] Review whether existing fields like filename support this?
- [ ] If not, index s3 path (arn + object key)
- [ ] Allow search by object key 
- [ ] Return IM UUID in response payload

### PR DESCRIPTION
**Pull request by YangusKhan**
closes #1430 

The big feature here is the addition of a `fieldQuery` query type, which takes a `field` and `value` to search against, and supports (single-level) nested fields. Unlike the full-text search, this is only useful for non-text fields and I added a boolean parameter to control whether the query is ran as a `match` or a `wildcard`, defaulting to `match`. In the `openapi.yml` I specifically included an enum whitelist of the valid `fields` you can query against, but I did not include app-level validation for that so it's only enforced at the schema validation level. I mostly did that because I wasn't sure if that was the best approach or if I should not have a whitelist at all and the search API user can just search against any field they want.

This PR also changes the `linkProtocols` facet to pull from the nested field `links.linkProtocol` instead of the `linkProtocol` field that we are pulling out separately. However, I did not remove the `linkProtocol` field from the search interfaces to try and keep in-line with our deprecation policy.

### CODE REVIEW

**Comment by mcquinne** [comment]
Alright so I did an experiment where I added `gcmdScience` to the `fieldQuery` spec and was able to successfully run a collection query and get what I expected with a request body like:

```json
{"queries":[{"type":"fieldQuery", "field":"gcmdScience", "value":"Atmosphere"}]}
```

However, it occurred to me that we clearly already have this capability because it's how the facet menu works. And lo and behold, I can replicate the same results (disregarding order) with the `facet` type in a **filtered** request, like so:

```json
{"filters":[{"type":"facet", "name":"science", "values":["Atmosphere"]}]}
```

So now I'm wondering if what we're really doing in this story is extending the existing `"type":"facet"` filtering capability to handle these new, nested fields? In fact, by tweaking the openapi again and adding `links.linkUrl` to [DocumentationService#facetNameMappings](https://github.com/cedardevs/onestop/blob/master/search/src/main/java/org/cedar/onestop/api/search/service/DocumentationService.java#L9) I was actually able to replicate the new link url query by using that existing facet filter like this:

```json
{"filters":[{"type":"facet", "name":"links.linkUrl", "values":["https://data.nodc.noaa.gov/ndbc/co-ops/"]}]}
```

This approach also has the added benefit of producing a [non-scoring query when we talk to Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html#filter-context), which should improve performance (on paper at least).

So here's my proposal for next steps:
1. Remove the new `fieldQuery` type 😢 
2. Ensure that all the nested fields that you've recently made indexed are valid options in the `facet` filter type
3. Upgrade the `facet` filter type to support the `"exactMatch": [true|false]` option that you implemented

@YangusKhan what do you think?

**Comment by YangusKhan** [comment]
@mcquinne 

So, if we add more facet filters, I think we would then need to re-evaluate the business logic that exists in the OneStop UI, because currently the UI parses all the facet aggregations returned by the search API and outputs them as filterable checkbox fields. I don't think that would make sense for _all_ of the new searchable fields, and definitely not for `links.linkUrl`, since the UI would produce a list of every single unique URL that belongs to all granules in a collection, for example, and I doubt that's what we want to have in the UI.

We could figure out a way to address that issue though then I think it would be fine to go with your proposal.

**Comment by mcquinne** [comment]
Yep, @YangusKhan is totally correct, adding to the `facetNameMappings` will also result in additional aggregation queries which won't make sense; definitely don't want to display all options for all keyword fields in a menu on the left. Still, I think we can combine the logic of the two approaches to help consolidate the implementation and make the API consistent.

So, new proposal!
1. Rename `"type":"fieldQuery"` to `"type":"field"` 
2. Move it under the `filters` context in the request structure
3. Make its structure match the `"type":"facet"` filter
4. Preserve the `"exactMatch": true|false` attribute
5. Consolidate implementation internally for both facet and field filters
6. Update openapi and tests accordingly

I'll give this a shot and push a commit

**Comment by mcquinne** [comment]
I was able to do the things mentioned above with the exception of allowing multiple `values` the way the facet filter does, because the underlying `wildcard` query type does not support multiple values. We could've worked around that by making a more complex query but decided that querying with multiple wildcards using OR logic doesn't really make sense; just write a better wildcard statement!

@YangusKhan I'm good with merging this now if you are.

**Review by mcquinne — APPROVED** [review]

**Pull request merged**
